/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardCard: typeof import('./src/components/awardCard.vue')['default']
    BannerSwiper: typeof import('./src/components/bannerSwiper.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DialogCloseBtn: typeof import('./src/components/dialogCloseBtn.vue')['default']
    DogsCard: typeof import('./src/components/dogsCard.vue')['default']
    FloatingBtn: typeof import('./src/components/floatingBtn.vue')['default']
    LogOutBtn: typeof import('./src/components/logOutBtn.vue')['default']
    OrderInfoCard: typeof import('./src/components/orderInfoCard.vue')['default']
    OrderList: typeof import('./src/components/orderList.vue')['default']
    PhotoCard: typeof import('./src/components/photoCard.vue')['default']
    PhotoCardSwiper: typeof import('./src/components/photoCardSwiper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/sectionTitle.vue')['default']
    TEST_Breakpointvue: typeof import('./src/components/TEST_Breakpointvue.vue')['default']
    UserAccountBg: typeof import('./src/components/userAccountBg.vue')['default']
    UserPhoto: typeof import('./src/components/userPhoto.vue')['default']
  }
}
