/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/dogInfo': RouteRecordInfo<'/admin/dogInfo', '/admin/dogInfo', Record<never, never>, Record<never, never>>,
    '/admin/manageBooking': RouteRecordInfo<'/admin/manageBooking', '/admin/manageBooking', Record<never, never>, Record<never, never>>,
    '/booking': RouteRecordInfo<'/booking', '/booking', Record<never, never>, Record<never, never>>,
    '/coolDogs': RouteRecordInfo<'/coolDogs', '/coolDogs', Record<never, never>, Record<never, never>>,
    '/dogsResume/[id]': RouteRecordInfo<'/dogsResume/[id]', '/dogsResume/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settingsConfig': RouteRecordInfo<'/settingsConfig', '/settingsConfig', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/userZone/': RouteRecordInfo<'/userZone/', '/userZone', Record<never, never>, Record<never, never>>,
    '/userZone/adaptiveTestResult': RouteRecordInfo<'/userZone/adaptiveTestResult', '/userZone/adaptiveTestResult', Record<never, never>, Record<never, never>>,
    '/userZone/dogBookingSearch': RouteRecordInfo<'/userZone/dogBookingSearch', '/userZone/dogBookingSearch', Record<never, never>, Record<never, never>>,
    '/userZone/favorite': RouteRecordInfo<'/userZone/favorite', '/userZone/favorite', Record<never, never>, Record<never, never>>,
  }
}
