# Action 名稱
name: Deploy
# 觸發時機，當推送到分支 main 時
on:
  push:
    branches: [main]
# 執行的工作
jobs:
  # 工作名稱
  deploy:
    # 執行工作的虛擬機作業系統
    runs-on: ubuntu-latest
    # 工作步驟
    steps:
      # 步驟一：複製程式碼
      - name: checkout
        # 使用的 actions/checkout 複製程式碼
        uses: actions/checkout@v3
      # 步驟二：編譯
      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          VITE_API: ${{ secrets.VITE_API }}

      # ✅ 新增：建立 .nojekyll
      # 避免 GitHub Pages 使用 Jekyll 處理檔案時，忽略 _ 開頭的檔案，而導致轉跳至網頁 4040
      # 例如：[id].vue 的檔案，[id] 是動態路由的命名方式，Vite 編譯時把 [ ] 轉成 _，所以一定會產生 _ 開頭的檔案。
      - name: Add .nojekyll
        run: touch dist/.nojekyll

      # 步驟三：部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.5
        with:
          branch: gh-pages
          folder: dist
          # clean 在每次部署前，先把 gh-pages 分支「舊的檔案全部刪掉」，再上傳新的 dist，防止「舊 build 檔案殘留」導致 JS chunk 404 / dynamic import error
          clean: true
